import type { ActivityEvent, Task } from './types'

export const tasks: Task[] = [
  {
    id: 'MC-1',
    title: 'Build Mission Control app skeleton',
    objective: 'Create the initial board, activity panel, and task detail structure.',
    acceptanceCriteria: [
      'Board columns render canonical states',
      'Activity feed is visible',
      'Task detail shows structured sections',
    ],
    boundaries: ['No backend yet', 'No Discord wiring yet'],
    status: 'in_progress',
    projectId: 'mission-control',
    type: 'code',
    requiresApproval: false,
    priority: 'high',
    createdBy: 'tony',
    source: 'chat',
    assignee: 'celine',
    needsUiTest: true,
    tags: ['mvp', 'ui'],
    plan: [
      { id: 's1', label: 'Define data model slices for MVP', status: 'done' },
      { id: 's2', label: 'Build board layout', status: 'done' },
      { id: 's3', label: 'Build task detail panel', status: 'in_progress' },
      { id: 's4', label: 'Add activity stream', status: 'pending' },
    ],
    currentStepIndex: 2,
    nextStep: 'Wire sample events and doc-sync badges',
    activeRunId: 'RUN-1',
    lastEventAt: '2026-03-15T22:35:00-07:00',
    createdAt: '2026-03-15T22:10:00-07:00',
    updatedAt: '2026-03-15T22:35:00-07:00',
    specVersionSeen: 'v1',
    requiresSpecUpdate: false,
    docSyncStatus: 'in_sync',
    lastDocSyncAt: '2026-03-15T22:00:00-07:00',
  },
  {
    id: 'MC-2',
    title: 'Implement local task store',
    objective: 'Create a local-first store that can drive board state changes.',
    acceptanceCriteria: ['Tasks persist locally', 'Transitions are validated'],
    status: 'triage',
    projectId: 'mission-control',
    type: 'code',
    requiresApproval: false,
    priority: 'high',
    createdBy: 'celine',
    source: 'system',
    assignee: 'celine',
    needsUiTest: false,
    plan: [
      { id: 's1', label: 'Choose local storage model', status: 'pending' },
      { id: 's2', label: 'Build transition helpers', status: 'pending' },
    ],
    lastEventAt: '2026-03-15T22:20:00-07:00',
    createdAt: '2026-03-15T22:20:00-07:00',
    updatedAt: '2026-03-15T22:20:00-07:00',
    specVersionSeen: 'v1',
    requiresSpecUpdate: false,
    docSyncStatus: 'in_sync',
    lastDocSyncAt: '2026-03-15T22:00:00-07:00',
  },
  {
    id: 'MC-3',
    title: 'Design runner pickup contract',
    objective: 'Define atomic pickup rules and stale-run handling.',
    acceptanceCriteria: ['Single-run lock model is documented'],
    status: 'backlog',
    projectId: 'mission-control',
    type: 'doc',
    requiresApproval: false,
    priority: 'medium',
    createdBy: 'celine',
    source: 'system',
    assignee: 'celine',
    needsUiTest: false,
    plan: [{ id: 's1', label: 'Write runner notes', status: 'pending' }],
    lastEventAt: '2026-03-15T22:15:00-07:00',
    createdAt: '2026-03-15T22:15:00-07:00',
    updatedAt: '2026-03-15T22:15:00-07:00',
    specVersionSeen: 'v1',
    requiresSpecUpdate: false,
    docSyncStatus: 'in_sync',
    lastDocSyncAt: '2026-03-15T22:00:00-07:00',
  },
  {
    id: 'MC-4',
    title: 'Connect Discord notification pipeline',
    objective: 'Send required state-change notifications to céline-notification.',
    acceptanceCriteria: ['Required events notify successfully'],
    boundaries: ['Do not spam the channel'],
    status: 'blocked',
    projectId: 'mission-control',
    type: 'ops',
    requiresApproval: true,
    priority: 'high',
    createdBy: 'celine',
    source: 'system',
    assignee: 'celine',
    needsUiTest: false,
    plan: [{ id: 's1', label: 'Confirm integration path', status: 'pending' }],
    blockerDetail: 'Waiting for app-side notification implementation in a later phase.',
    lastEventAt: '2026-03-15T22:25:00-07:00',
    createdAt: '2026-03-15T22:25:00-07:00',
    updatedAt: '2026-03-15T22:25:00-07:00',
    specVersionSeen: 'v1',
    requiresSpecUpdate: false,
    docSyncStatus: 'deferred',
    lastDocSyncAt: '2026-03-15T22:00:00-07:00',
  },
  {
    id: 'MC-5',
    title: 'Publish Mission Control spec to GitHub',
    objective: 'Push current workspace repo without insurance app contents.',
    acceptanceCriteria: ['Repo exists on GitHub', 'TuanInsurance is excluded'],
    status: 'done',
    projectId: 'mission-control',
    type: 'ops',
    requiresApproval: false,
    priority: 'medium',
    createdBy: 'tony',
    source: 'chat',
    assignee: 'celine',
    needsUiTest: false,
    plan: [{ id: 's1', label: 'Create repo and push', status: 'done' }],
    lastEventAt: '2026-03-15T22:25:00-07:00',
    createdAt: '2026-03-15T22:22:00-07:00',
    updatedAt: '2026-03-15T22:25:00-07:00',
    completedAt: '2026-03-15T22:25:00-07:00',
    specVersionSeen: 'v1',
    requiresSpecUpdate: false,
    docSyncStatus: 'in_sync',
    lastDocSyncAt: '2026-03-15T22:25:00-07:00',
  },
]

export const activity: ActivityEvent[] = [
  {
    id: 'A-1',
    taskId: 'MC-5',
    projectId: 'mission-control',
    type: 'done',
    title: 'Workspace repo published to GitHub',
    body: 'Created public repo and excluded TuanInsurance from publish.',
    createdAt: '2026-03-15T22:25:00-07:00',
    createdBy: 'celine',
  },
  {
    id: 'A-2',
    taskId: 'MC-1',
    projectId: 'mission-control',
    type: 'progress',
    title: 'App skeleton implementation started',
    body: 'Building board, activity feed, and structured task detail surface.',
    createdAt: '2026-03-15T22:35:00-07:00',
    createdBy: 'celine',
  },
  {
    id: 'A-3',
    taskId: 'MC-2',
    projectId: 'mission-control',
    type: 'task_picked_up',
    title: 'Local store task queued for next phase',
    createdAt: '2026-03-15T22:20:00-07:00',
    createdBy: 'system',
  },
  {
    id: 'A-4',
    taskId: 'MC-4',
    projectId: 'mission-control',
    type: 'blocked',
    title: 'Notification pipeline blocked',
    body: 'Needs implementation path after local MVP UI exists.',
    createdAt: '2026-03-15T22:25:00-07:00',
    createdBy: 'celine',
  },
]
